### PR TITLE
Compilation fix

### PR DESCRIPTION
**Pull request by cossorzano**

### CODE REVIEW

**Comment by DStrelak** [comment]
Hi @cossorzano ,
which compiler reports errors in these?

**Comment by cossorzano** [comment]
g++ - v gives

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

I agree that it is an old compiler, but it is the one that xmipp config has taken from /usr/bin. There is in the same directory one called /usr/bin/g++-7, but it was not found by the script.

**Comment by DStrelak** [comment]
Yeah, that one is quite old.
I don't have anything against these changes, however, they are not important, as we plan to switch to c++14 (i.e. we will require newer compiler that 4.8 anyway).
I'm aware that we take the first compiler that we find, without checking if there's newer. That should be improved in the future version

**Comment by cossorzano** [comment]
Maybe a solution for the compiler would be checking for the existence of g++-7, g++-6, g++-5, ..., and if not g++

**Review by horacekj — APPROVED** [review]

**Pull request merged**
