### PR TITLE
Added support for half precision floating point numbers in MRCs

### PR DESCRIPTION
**Pull request by oierlauzi**
Xmipp is now able to read and write from FP16 (mode 12) MRC files. To do so, I have integrated the [half 2.2.0](https://sourceforge.net/projects/half/) library into Xmipp's codebase. This library will use intrinsic instructions to perform the conversion when available.

### CODE REVIEW

**Comment by oierlauzi** [comment]
I am pending to get some FP16 MRC files to be able to test changes and make definitive this pull request.

**Comment by oierlauzi** [comment]
Codesmells are coming from the half library.

**Comment by albertmena** [comment]
> Codesmells are coming from the half library.

The most of the yes but 
image

**Comment by oierlauzi** [comment]
> The half 2.2.0 is compatible with C++17?, the web says
> 
> > supporting C++11 features
> > Not sure what it means

It should be. "supporting C++11 features" means that it takes advantage of modern C++ features when available (such as `constexpr`). AFAIK It should be compatible with any C++ version, including C++17

**Comment by albertmena** [comment]
Please, review the error in the compillation:
https://github.com/I2PC/xmippCore/actions/runs/4664979447/jobs/8257807619?pr=170

**Comment by oierlauzi** [comment]
> Please, review the error in the compillation: https://github.com/I2PC/xmippCore/actions/runs/4664979447/jobs/8257807619?pr=170

Ooops, fixed it. I do not why it was compiling in my machine, as there was an error there

**Comment by albertmena** [comment]
> > Please, review the error in the compillation: https://github.com/I2PC/xmippCore/actions/runs/4664979447/jobs/8257807619?pr=170
> 
> Ooops, fixed it. I do not why it was compiling in my machine, as there was an error there

It appears after the merge devel into the branch

**Comment by oierlauzi** [comment]
There was another compilation issue. Fixed it

**Review by albertmena — APPROVED** [review]

**Pull request merged**
