### PR TITLE
Added support for reading movies in EER format

### PR DESCRIPTION
**Pull request by oierlauzi**

### CODE REVIEW

**Comment by oierlauzi** [comment]
EER files are a bit special as rendering parameters need to be provided. To do so, these parameters are appended to de filename with a preceding `#`:

`path/to.eer#A,B,C`

where 

- A is the number of frames, typically 32 or 40
- B is the the image size. Must be `4K` or `8K`
- C is the bit-depth. Must be `uint8` or `uint16`

**Comment by albertmena** [comment]
xmipp_image_convert -i /home/agarcia/Downloads/FoilHole_29355520_Data_29330528_29330530_20200329_234551_Fractions.mrc.eer#32,4k,uint8  -o /home/agarcia/Downloads/EER_out.mrc.eer
`Aborted (core dumped)`

**Review by albertmena — APPROVED** [review]

**Comment by albertmena** [comment]
> Something I'm doing wrong?
> 
> `xmipp_image_convert -i /home/agarcia/Downloads/FoilHole_29355520_Data_29330528_29330530_20200329_234551_Fractions.mrc.eer#32,4k,uint8 -o /home/agarcia/Downloads/EER_out.mrc.eer` **Aborted (core dumped)**

`./xmipp cleanBin` and `./xmipp`
After that it works, just a warning (not sure the reason)
`TIFFReadDirectory: Warning, Unknown field with tag 65001 (0xfde9) encountered.`

**Comment by oierlauzi** [comment]
> > Something I'm doing wrong?
> > `xmipp_image_convert -i /home/agarcia/Downloads/FoilHole_29355520_Data_29330528_29330530_20200329_234551_Fractions.mrc.eer#32,4k,uint8 -o /home/agarcia/Downloads/EER_out.mrc.eer` **Aborted (core dumped)**
> 
> `./xmipp cleanBin` and `./xmipp` After that it works, just a warning (not sure the reason) `TIFFReadDirectory: Warning, Unknown field with tag 65001 (0xfde9) encountered.`

Warnings are normal, as EER makes use of non-standard TIFF tags

**Pull request merged**
