### PR TITLE
Improved MultidimArray performance

### PR DESCRIPTION
**Pull request by oierlauzi**
Tried to fix 2 issues regarding MultidimArray performance.

- Added move constructor and move assignment. This improves performance when a R-value is asssigned. 
- Modified copies when resizing to make use of `memcpy` instead of manual copies.

### CODE REVIEW

**Comment by oierlauzi** [comment]
Program tests have succeed. Protocol tests are still ongoing

**Comment by albertmena** [comment]
> Program tests have succeed. Protocol tests are still ongoing

Protocol tests pass, at least the ones passed before this branch

**Comment by albertmena** [comment]
Could you provide a small summary about the impact of this implementation? speedup of programs? which one?. If performance optimization were applied, we must inform about it in the next release

**Review by albertmena — APPROVED** [review]

**Comment by albertmena** [comment]
merge devel into this branch and resolve the conflict please

**Comment by albertmena** [comment]
Better performance of resizeCopy and resize in multdimarray and also in structures std::vector<Multidimarray>

**Pull request merged**
