### PR TITLE
Automatic mapping of Unknown labels using Buffer ones

### PR DESCRIPTION
**Pull request by delarosatrevin**
Changes in this PR:
* Now when reading star files, if an unknown label is found, it will be mapped to a free buffer one
* Removed all BSOFT labels (all string, so it will be properly mapped) because of performance reasons: each label will increase the memory required by a MetaData Row.

This PR extends the solution by @pconesa and @rmarabini with the buffer labels, but it passed the responsibility to Python binding to have the mappings for each package...and also it was not applicable to the showj viewer in Java. This two issues are solved now with the changes proposed here.

Constant definition in the Python Binding and test is in the xmipp repo PR, in my opinion these should be part of the core, as this split commit clearly shows.

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Yes, I added a few tests here: https://github.com/I2PC/xmipp/pull/28/files
It is weird that the tests for the core classes are not in this repo but in the Xmipp one.
Even more weird, @dmaluenda told that those tests (e.g test_metadata_main) are no longer supported from the split of the repos and the test were not running before this PR...so, no real way to test here.
I have tested in my branch of scipion/xmipp based on v1.2.1 where I originally introduced these changes.

**Comment by dmaluenda** [comment]
I don't know why, but these tests was not being tested from (at least) 1 year ago. I understand that they are important, so we will do the best to include them in the regular tests as soon as possible.

Regarding the place where to put that tests, I can agree in put it in this repo but it is using the xmipp_image_convert.h file from the Xmipp repo... (in principle, we have split the code in such a way that xmippCore is not depending on any other repo). However, I think that all this thinks can be addressed to the next version... tempus fugit...

**Comment by dmaluenda** [comment]
@rmarabini @pconesa @cossorzano, how do you think this PR? All tests I run have been passed.

If no inconvenient, I'll merge this and [PR:xmipp#28](https://github.com/I2PC/xmipp/pull/28).

**Comment by pconesa** [comment]
It's ok for me. Haven0t tested it but is out of my skills...and I you and @delarosatrevin have tested this I think is enough.

**Pull request merged**
